config/routes.rb
GoLumber::Application.routes.draw do

  root :to => 'products#search'
  match 'products/table' => 'products#table'
  match 'products/update_search_selects' => 'products#update_search_selects'
  resources :home
  resources :units
  resources :referrals
  resources :about, :only => [:index]
  resources :privacy, :only => [:index]
  resources :terms, :only => [:index]
  resources :faq, :only => [:index]
  resources :contacts, :only => [:index, :create]

  resources :companies
  resources :products
  resources :photos
  resources :mailing_lists
  resources :species, :only => [:index, :create, :new, :show, :destroy]
  resources :grades, :only => [:index, :create, :new, :show, :destroy]
  resources :employees
    
  devise_for :employees, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :passwords => 'devise/passwords', :sign_up => 'registration'}
  devise_for :employees, :controllers => {:confirmations => "confirmations", :registrations => "registrations"}
  devise_scope :employees do
    put "confirm_account", :to => "confirmations#confirm_account"
  end
 

end

app/models/mailing_list.rb
class MailingList < ActiveRecord::Base
  attr_accessible :company_id, :contact_first, :contact_last, :email
  belongs_to :company
  
  validates :company_id, :presence => true
  validates :email,      :presence => true,
                         :length => { :minimum => 5 }
end

app/controllers/mailing_lists_controller.rb
class MailingListsController < ApplicationController
  # GET /mailing_lists
  # GET /mailing_lists.json
  before_filter :auth_employee
  
  def index
    @mailing_lists = MailingList.where(:company_id => current_employee.company_id)
    @mailing_lists = @mailing_lists.sort_by! { |email| [email.email] }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mailing_lists }
    end
  end

  # GET /mailing_lists/1
  # GET /mailing_lists/1.json
  def show
    @mailing_list = MailingList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mailing_list }
    end
  end

  # GET /mailing_lists/new
  # GET /mailing_lists/new.json
  def new
    @mailing_list = MailingList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mailing_list }
    end
  end

  # GET /mailing_lists/1/edit
  def edit
    @mailing_list = MailingList.find(params[:id])
  end

  # POST /mailing_lists
  # POST /mailing_lists.json
  def create
    @employee = current_employee
    @company = Company.find(@employee.company_id)
    @mailing_list = @company.mailing_lists.create(params[:mailing_list])
    # Ensure that the names are capitalized for uniformity
    @mailing_list[:contact_first] = proper_name(@mailing_list[:contact_first])
    @mailing_list[:contact_last] = proper_name(@mailing_list[:contact_last])

    respond_to do |format|
      if @mailing_list.save
        format.html { redirect_to @mailing_list, notice: 'Mailing list was successfully created.' }
        format.json { render json: @mailing_list, status: :created, location: @mailing_list }
      else
        format.html { render action: "new" }
        format.json { render json: @mailing_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mailing_lists/1
  # PUT /mailing_lists/1.json
  def update
    @mailing_list = MailingList.find(params[:id])

    respond_to do |format|
      if @mailing_list.update_attributes(params[:mailing_list])
        format.html { redirect_to @mailing_list, notice: 'Mailing list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mailing_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mailing_lists/1
  # DELETE /mailing_lists/1.json
  def destroy
    @mailing_list = MailingList.find(params[:id])
    @mailing_list.destroy

    respond_to do |format|
      format.html { redirect_to mailing_lists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mailing_lists_helper.rb
module MailingListsHelper
end

app/views/mailing_lists/_form.html.erb
<div class="specialForms">
<%= form_for(@mailing_list) do |f| %>
	<% if @mailing_list.errors.any? %>
   		<div id="error_explanation">
     		<h2><%= pluralize(@mailing_list.errors.count, "error") %> prohibited this mailing_list from being saved:</h2>
      		<ul>
      		<% @mailing_list.errors.full_messages.each do |msg| %>
        		<li><%= msg %></li>
      		<% end %>
      			</ul>
	    </div>
	<% end %>
	
 	<div class="field">
    	<%= f.label :email %><br />
	    <%= f.text_field :email %>
  	</div>
  	<div class="field">
    	<%= f.label :contact_first %><br />
	    <%= f.text_field :contact_first %>
  	</div>
  	<div class="field">
    	<%= f.label :contact_last %><br />
    	<%= f.text_field :contact_last %>
  	</div>
  	<div class="field">
  		<%= f.hidden_field :company_id, :value => current_employee.company_id %>
    </div>
  	<div class="actions">
    	<ul>
    		<li><%= f.submit("Add Contact", :class => "genericButton")  %></li>
    	</ul>
  	</div>
<% end %>
</div>

app/views/mailing_lists/edit.html.erb
<div id="container">	
	<div id="content">
		<h1>Editing Mailing List Entry</h1>
		<div id="MainText" class="gradient2">
			<div id="addContainer">
				<%= render 'form' %>
			</div>
		</div>
				<div class= "footer">
					<%=render :partial => 'layouts/footer'%>
				</div>
	</div>
</div>

app/views/mailing_lists/index.html.erb
<head>

</head>
<body>
	<div id="container">	
		<div id="content">
			<h1>Mailing List</h1>
			<div id="holder">
				<button id="sendNow" class="genericButton rightfloater">Send Now</button>	
				<button id="previewStock" class="genericButton rightfloater">Preview Inventory Stock Sheet</button>				
			</div><!-- end div#holder -->
			
			<div id="MainText" class="gradient2">
				<h3>Inventory Distribution List</h3>
				<div class="rightfloater">
					<%= button_to 'Add Contact', new_mailing_list_path, :method => :get, :class => "genericButton" %>
				</div>
				
				<table id="emailList">
					<% @mailing_lists.each do |mailing_list| %>
	  					<tr id="productRows">
	    					<td><%= mailing_list.email %></td>
	    					<td><%= mailing_list.contact_first %></td>
	    					<td><%= mailing_list.contact_last %></td>
	    					<td id="editRemove"><%= button_to  'Remove', mailing_list, :method => :delete, :confirm => "Are you sure you wish to delete #{mailing_list.contact_first} #{mailing_list.contact_last}?" , :class => "genericButton"%></td>
	  					</tr>
					<% end %>
				</table>
			</div><!-- end div#MainText -->
			<div class= "footer">
				<%=render :partial => 'layouts/footer'%>
			</div>
		</div>
		</div> <!-- end div#content -->
	</div> <!-- end div#container -->

</body>

app/views/mailing_lists/new.html.erb
<div id="container">	
	<div id="content">
		<h1>Mailing List</h1>
		<div id="MainText" class="gradient2">
		<div id="addContainer">
			<%= render 'form' %>
			<%= link_to 'My Mailing List', mailing_lists_path %>
			
		</div>
		</div>
				<div class= "footer">
					<%=render :partial => 'layouts/footer'%>
				</div>
		</div>
		</div>

app/views/mailing_lists/show.html.erb
<div id="container">	
	<div id="content">
		<h1>Mailing List</h1>
		<div id="MainText" class="gradient2">
			<div id="addContainer">

<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @mailing_list.email %>
</p>

<!-- <p>
  <b>Contact first:</b>
  <%= @mailing_list.contact_first %>
</p>

<p>
  <b>Contact last:</b>
  <%= @mailing_list.contact_last %>
</p> -->


<%= link_to 'Edit', edit_mailing_list_path(@mailing_list) %> |
<%= link_to 'My Mailing List', mailing_lists_path %>

			</div>
		</div>
				<div class= "footer">
					<%=render :partial => 'layouts/footer'%>
				</div>
	</div>
</div>