config/routes.rb
GoLumber::Application.routes.draw do

  root :to => 'products#search'
  match 'products/table' => 'products#table'
  match 'products/update_search_selects' => 'products#update_search_selects'
  resources :home
  resources :units
  resources :referrals
  resources :about, :only => [:index]
  resources :privacy, :only => [:index]
  resources :terms, :only => [:index]
  resources :faq, :only => [:index]
  resources :contacts, :only => [:index, :create]

  resources :companies
  resources :products
  resources :photos
  resources :mailing_lists
  resources :species, :only => [:index, :create, :new, :show, :destroy]
  resources :grades, :only => [:index, :create, :new, :show, :destroy]
  resources :employees
    
  devise_for :employees, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :passwords => 'devise/passwords', :sign_up => 'registration'}
  devise_for :employees, :controllers => {:confirmations => "confirmations", :registrations => "registrations"}
  devise_scope :employees do
    put "confirm_account", :to => "confirmations#confirm_account"
  end
 

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_filter :auth_employee
	#has ability requires the company_id so use the product to find the company id
	before_filter( :only => [:edit, :delete, :show]) { |c| c.has_ability Product.where(:id => params[:id]).first.company_id }

	def search
		@species = Species.joins(:products).where('products.is_active' => true).select("distinct(species.id), species.name")
		@results_tag = "Featured"
		@products = Product.all.sort_by { rand }.slice(1,15)
		@products = @products.sort_by! { |product| [
			product.species.name, product.thickness_metric,
			product.width_metric, (product.grade.name).reverse] }
	end
	
	def update_search_selects
		if params["species"].nil?
			@species = Species.joins(:products).where('products.is_active' => true).select("distinct(species.id), species.name")
		else
			@imperial = params["imperial"] == 'true'
			@selected_species = params["species"].to_i
			if params["thickness"].nil?
				if @imperial
					@thicknesses_imperial = Product.where('species_id = ? AND thickness_imperial != ""', @selected_species)
					 															.select("distinct(thickness_imperial) as distinct_thickness, 'imperial' as type")
					@thicknesses_actual = Product.where('species_id = ? AND thickness_imperial = ""', @selected_species)
																				.select("distinct(thickness_actual) as distinct_thickness, 'actual' as type")
					@thicknesses = @thicknesses_imperial + @thicknesses_actual
				else
					@thicknesses = Product.where(:species_id => @selected_species).select("distinct(thickness_metric) as distinct_thickness, 'metric' as type")
				end
			else
				@selected_thickness = params["thickness"]
				@selected_thickness_type = params["thickness_type"]
				if params["width"].nil?
					if @imperial
						@widths_imperial = Product.where('species_id = %s AND thickness_%s = %s AND width_imperial != ""', @selected_species, @selected_thickness_type, @selected_thickness)
																					.select("distinct(width_imperial) as distinct_width, 'imperial' as type")
						@widths_actual = Product.where('species_id = %s AND thickness_%s = %s AND width_imperial = ""', @selected_species, @selected_thickness_type, @selected_thickness)
																					.select("distinct(width_actual) as distinct_width, 'actual' as type")
						@widths = @widths_imperial + @widths_actual
					else
						@widths = Product.where(:species_id => @selected_species, :thickness_metric => @selected_thickness).select("distinct(width_metric) as distinct_width, 'metric' as type")
					end
				else
					@selected_width = params["width"]
					@selected_width_type = params["width_type"]
					@grades = Product.joins(:grade).where("species_id = %s AND thickness_%s = %s AND width_%s = %s", @selected_species, @selected_thickness_type, @selected_thickness, @selected_width_type, @selected_width).select("distinct(grades.id), grades.name")
				end
			end
		end
		respond_to do |format|
			 format.js
		end
	end
	
	def table
		@employee = current_employee
    @company = @employee.company
		@imperial = params["imperial"] == 'true'
		@activityColumn = false
		@search = params["search"] == 'true'
		if @search
      @results_tag = "Results"
			@products = Product.where("species_id = %s AND thickness_%s = %s AND width_%s = %s AND grade_id = %s", params["species"], params["thickness_type"], params["thickness"], params["width_type"], params["width"], params["grade"])
		else
			case params["display"]
				when "all"
					@products = @company.products
					@activityColumn = true
				when "active"
					@products = @company.products.where(:is_active => true)
				else
					@products = @company.products.where(:is_active => false)
			end
			@products = @products.sort_by! {
				|product| [product.species.name, product.thickness_metric, 
				product.width_metric, (product.grade.name).reverse] }
		end
		respond_to do |format|
			format.js
		end
	end

	# GET /products
	# GET /products.json
	def index
		@employee = current_employee
		@company = @employee.company
		@products = Product.where(:company_id => @company.id)
		@products = @products.sort_by! { |product| [product.species.name, product.thickness_metric, 
																								product.width_metric,
																								(product.grade.name).reverse] }
		@company_employee = Employee.where(:company_id => @company.id).first
		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @products }
		end
	end

	# GET /products/1
	# GET /products/1.json
	def show
		@product = Product.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @product }
		end
	end

	# GET /products/new
	# GET /products/new.json
	def new
		@product = Product.new
		@company = current_employee.company
		@product.photos.build

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @product }
		end
	end

	# GET /products/1/edit
	def edit
		@product = Product.find(params[:id])
		@product.photos.build
		@company = @product.company
	end

	# POST /products
	# POST /products.json
	def create
		# add the company id to the associated product
		@product = Product.new
		@company = current_employee.company
		if params[:random_width]
			params[:product][:width_imperial] = 0
			params[:product][:width_actual] = 0
			params[:product][:width_metric] = 0
		end
		newParams = params[:product].merge(:company_id => current_employee.company_id)
		unit = params[:unit]
		if unit == "metric"
			@product.validateMetric(newParams)
		else
			@product.validateImperial(newParams)
		end
		respond_to do |format|
			if not(@product.errors.blank?)
				@product.photos.build
				@product.attributes = newParams #Sends the filled in fields to be rendered with the errors
				format.html { render action: "new" }
				format.json { render json: @product.errors, status: :unprocessable_entity }
			else
				if unit == "metric"
					final_params = @product.convertProductToImperial(newParams)
				else
					final_params = @product.convertProductToMetric(newParams)
				end
				@product.attributes = final_params
				if @product.update_attributes(final_params)
					format.html { redirect_to products_url, notice: 'Product was successfully created.' }
					format.json { render json: @product, status: :created, location: @product }
				else
					format.html { render action: "new" }
					format.json { render json: @product.errors, status: :unprocessable_entity }
				end
			end
		end #end do
		if (params[:product][:photos_attributes])
			params[:product][:photos_attributes].each do |photo_attributes_array|
				photo_attributes = photo_attributes_array[1]
				if !photo_attributes[:photo].nil?
					@photo = @product.photos.build(photo_attributes)
					@photo.save
				end
			end		
		end
	end

	# PUT /products/1
	# PUT /products/1.json
	def update
		@product = Product.find(params[:id])
		newParams = params[:product].merge(:company_id => current_employee.company_id)
		unit = params[:unit]
		if unit == "metric"
			@product.validateMetric(newParams)
		else
			@product.validateImperial(newParams)
		end

		respond_to do |format|
			if not(@product.errors.blank?)
				@product.attributes = newParams #Sends the filled in fields to be rendered with the errors
				format.html { render action: "edit" }
				format.json { render json: @product.errors, status: :unprocessable_entity }
			else
				if unit.to_s == "metric"
					final_params = @product.convertProductToImperial(newParams)
				elsif unit.to_s == "imperial"
					final_params = @product.convertProductToMetric(newParams)
				end
				@product.attributes = final_params
				if @product.update_attributes(final_params)
					format.html { redirect_to products_url, notice: 'Product was successfully updated.' }
					format.json { head :no_content }
				else
					format.html { render action: "edit" }
					format.json { render json: @product.errors, status: :unprocessable_entity }
				end
			end
		end #end do
		if(params[:product][:photos_attributes])
			params[:product][:photos_attributes].each do |photo_attributes_array|
				photo_attributes = photo_attributes_array[1]
				if !photo_attributes[:photo].nil?
					@photo = @product.photos.build(photo_attributes)
					@photo.save
				end
			end		
		end
	end
	
	# DELETE /products/1
	# DELETE /products/1.json
	def destroy
		@product = Product.find(params[:id])
		@product.destroy

		respond_to do |format|
			format.html { redirect_to products_url }
			format.json { head :no_content }
		end
	end
end

app/helpers/products_helper.rb
module ProductsHelper
	def addUpdateProductsOnChange
		javascript_tag("addUpdateProductsOnChange()")
	end
	
# Displays a table containing the specified products' data in the specified units
# @param products: a relation containing all of the products to be displayed
#	    if products is empty, only the column headers will be displayed
# @param imperial: a boolean value specifying the units to display
#     true:  imperial will be displayed
#     false: metric will be displayed
# @param activityColumn: true if a column should be included to show whether the items are active
#	@param search: true if this is the search table, false if it is on an inventory page
#	    the search page includes a column for the product's company and that company's country
#	    the search page also allows you to scroll through the results 
	def productTable(products, imperial = true, activityColumn = false, search = false)
		render 'product_table', {:products => products, :imperial => imperial, :activityColumn => activityColumn, :search => search}
	end
	
# Displays a header row for a product table using the specified units
# @param imperial: a boolean value specifying the units to display
#     true:  imperial will be displayed
#     false: metric will be displayed
# @param activityColumn: true if a column should be included to show whether the items are active
	def productTableHeaders(imperial = true, activityColumn = false, search = false)
    render 'product_table_headers', {:imperial => imperial, :activityColumn => activityColumn, :search => search}
	end
	
# Displays a table row containing product's data in the same order as product_table_headers
# @param product: the product to be displayed
# @param imperial: a boolean value specifying the units to display
#     true: imperial will be displayed
#     false: metric will be displayed
# @param activityColumn: true if a column should be included to show whether the items are active
	def productTableRow(product, imperial = true, activityColumn = false, search = false)
    render 'product_table_row', {:product => product, :imperial => imperial, :activityColumn => activityColumn, :search => search}
	end
end

app/views/products/_form.html.erb
<%= form_for(@product, :html => {:novalidate => true, :multipart => true}) do |f| %>
	<% if @product.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

			<ul>
				<% @product.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<div id="topDiv">
 		<div class="field">
 			<% f.object.is_active = true %>
			<%= f.check_box :is_active, :class => "clearLeft", :tabindex => 1 %>
			<%= f.label :is_active, "Active" , :class => "smallLabel floatLeft" %>
		</div>
	  <div class="field">
		  <%= radio_button_tag "unit", "imperial", true, :class => "clearLeft", :tabindex => 2 %>
		  <%= label_tag "unit_imperial", "Imperial (inches or fractions)", :class => "smallLabel floatLeft" %>
		  <%= radio_button_tag "unit", "metric", false, :class => "clearLeft" %>
		  <%= label_tag "unit_metric", "Metric (millimeters)", :class => "smallLabel" %>
		</div>
	</div>
	
	<!-- <div id="middleDiv"> -->
		<div>
			<%= f.label :region, "Region*" %>
		</div>
		<div style="float: left; clear: left;">
			<%= f.select :region, options_for_select([
				"Alabama",
				"Alaska",
				"Arizona",
				"Arkansas",
				"California",
				"Colorado",
				"Connecticut",
				"Delaware",
				"DC",
				"Florida",
				"Georgia",
				"Hawaii",
				"Idaho",
				"Illinois",
				"Indiana",
				"Iowa",
				"Kansas",
				"Kentucky",
				"Louisiana",
				"Maine",
				"Maryland",
				"Massachusetts",
				"Michigan",
				"Minnesota",
				"Mississippi",
				"Missouri",
				"Montana",
				"Nebraska",
				"Nevada",
				"New Hampshire",
				"New Jersey",
				"New Mexico",
				"New York",
				"North Carolina",
				"North Dakota",
				"Ohio",
				"Oklahoma",
				"Oregon",
				"Pennsylvania",
				"Rhode Island",
				"South Carolina",
				"South Dakota",
				"Tennessee",
				"Texas",
				"Utah",
				"Vermont",
				"Virginia",
				"Washington",
				"West Virginia",
				"Wisconsin",
				"Wyoming",
				], :selected => f.object.region) %>
		</div>
		<br/>

		<div id="leftDiv" style="float: left; clear: left;">
			<div class="field" id="species">
				<br/>
				<%= f.label :species_id, "Species*", :class => "labelWithLink" %> 
				<%= link_to "Add Species", "/species/new" %>
				<%= f.select(:species_id, Species.order('name').collect {|c| [c.name, c.id]}, {:prompt => 'Select'}, :class => "clearLeft", :tabindex => 3) %>
			</div>
		</div>
			
			<div class="field imperial">
				<%= f.label :thickness_imperial, "Thickness (in)*", :class => "floatLeft" %>
				<%= f.label :thickness_actual, "Actual (in)*", :class => "floatLeft", :style => "margin-left:20px", :title => "very important for overseas buyers" %>
				<%= f.label :the_x, "X", :class => "floatLeft", :style => "margin-left:20px" %>
				<%= f.label :width_imperial, "Width (in)*", :class => "floatLeft", :style => "margin-left:20px" %>
				<%= f.label :width_actual, "Actual (in)*", :class => "floatLeft", :style => "margin-left:20px", :title => "very important for overseas buyers" %>
			</div>
			<div class="field imperial">
				<%= f.text_field :thickness_imperial, :class => "smallerInput imperialfield clearLeft", :style => "display: none;" %>
				<input type="text" name="product_thickness_imperial_dummy" id="product_thickness_imperial_dummy" class="smallerInput imperialfield clearLeft" tabindex="3">
				<%= f.number_field :thickness_actual, :class => "smallerInput imperialfield floatLeft", :tabindex => 4, :style => "margin-left:115px", :title => "very important for overseas buyers" %>
				<%= f.text_field :width_imperial, :class => "smallerInput imperialfield floatLeft", :style => "display:none" %>
				<input type="text" name="product_width_imperial_dummy" id="product_width_imperial_dummy" class="smallerInput imperialfield floatLeft" tabindex="5" style="margin-left:115px">
				<%= f.number_field :width_actual, :class => "smallerInput imperialfield floatLeft", :tabindex => 6, :style => "margin-left:75px", :title => "very important for overseas buyers" %>
			</div>
			<div class="field metric floatLeft" style="display:none;">
				<%= f.label :thickness_metric, "Thickness (mm)*", :class => "floatLeft" %>
				<%= f.label :the_x, "X", :class => "floatLeft", :style => "margin-left:20px" %>
				<%= f.label :width_metric, "Width (mm)*", :class => "floatLeft", :style => "margin-left:20px" %>
			</div>
			<div class="field metric floatLeft" style="display:none;">
				<%= f.number_field :thickness_metric, :class => "smallerInput metricfield clearLeft", :tabindex => 3 %>
				<%= f.number_field :width_metric, :class => "smallerInput metricfield floatLeft", :style => "margin-left:160px", :tabindex => 6 %>
			</div>

			<div class="field floatLeft">
			  <%= label_tag :random_width, "Random Width", :class => "smallLabel" %>
			  <%= check_box_tag :random_width, :tabindex => 7 %>
			</div>			
		
		<div class="field" id="grade">
			<%= f.label :grade_id, "Grade*", :class => "labelWithLink" %>
			<%= link_to "Add Grade", "/grades/new" %>
			<%= f.select(:grade_id, @company.grades.order('name').collect {|c| [c.name, c.id]}, {:prompt => 'Select'}, :class => "clearLeft", :tabindex => 8)%>
		</div>
		<div class="floatLeft", style="margin-left:50px">
			<div class="field metric" style="display:none;">
				<%= f.label :length, "Length (m)*", :class => "floatLeft" %>
				<%= f.label :cubic_meters, "Quantity (M3)*", :class => "floatLeft", :style => "margin-left:15px" %>
			</div>
			<div class="field metric" style="display:none;">
				<%= f.number_field :length_metric_lower, :class => "smallerInput metricfield clearLeft", :tabindex => 8 %>
				<%= f.number_field :length_metric_upper, :class => "smallerInput metricfield floatLeft", :style=>"visibility:hidden;", :tabindex => 9 %>
				<%= f.number_field :cubic_meters, :class => "smallerInput metricfield floatLeft", :style => "margin-left:40px", :tabindex => 11 %>
			</div>
			<div class="field imperial">
				<%= f.label :length, "Length (ft)*" %>
				<%= f.label :board_feet, "Footage (BF')*", :class => "floatLeft", :style => "margin-left:20px" %>
			</div>
			<div class="field imperial">
				<%= f.number_field :length_imperial_lower, :class => "smallerInput imperialfield clearLeft", :tabindex => 8 %>
				<%= f.number_field :length_imperial_upper, :class => "smallerInput imperialfield floatLeft", :style=>"visibility:hidden;", :tabindex => 9 %>
				<%= f.number_field :board_feet, :class => "smallerInput imperialfield floatLeft", :style => "margin-left:40px", :tabindex => 11 %>
			</div>
		</div>
		
	 	<div class="floatRight">
			  <div class="floatLeft" style="margin-right:10px">
			  <%= label_tag "length_input_single", "Single", :class => "smallLabel"%>
			  <%= radio_button_tag "length_input", "single", true, :tabindex => -1 %>
			</div>
		  <div class="floatLeft" style="margin-right:10px">
			  <%= label_tag "length_input_ranged", "Range", :class => "smallLabel", :title => "Example: 8-16'"%>
			  <%= radio_button_tag "length_input", "ranged" %>
			</div>
		  <div class="floatLeft" style="margin-right:10px">
			  <%= label_tag "length_input_random", "Random", :class => "smallLabel"%>
			  <%= radio_button_tag "length_input", "random" %>
			</div>
		</div>
	
	<div>
		<div class="field">
			<%= f.label :details, :class => "floatLeft" %>
			<%= f.text_area :details, :placeholder => "Any additional details concerning this product.", :class => "clearLeft", :tabindex => 12 %>
		</div>
		<%= render :partial => 'photos/edit_photos_fields', :locals => {:f => f, :imageable => @product} %>
	</div>
			
	<div class="actions clearLeft">
		<div><small>*Required Fields</small></div>
		<%= f.submit("Save", :class => "genericButton", :onClick => "ClearExtraFields()", :tabindex => 16) %>
	</div>

	<script type='text/javascript'>
	//<![CDATA[
	initializeProductForm();
	
	$(document).ready(function() {
		$(document).on("change","#product_thickness_imperial_dummy", function() {
			var imperial_thickness_val = $("#product_thickness_imperial_dummy").val();
			var parsed_imperial_thickness_val = eval(imperial_thickness_val);
			$("#product_thickness_actual").val(parsed_imperial_thickness_val);
			$("#product_thickness_imperial").val(parsed_imperial_thickness_val);
		}); 
		$(document).on("change","#product_width_imperial_dummy", function() {
			var imperial_width_val = $("#product_width_imperial_dummy").val();
			var parsed_imperial_width_val = eval(imperial_width_val);
			$("#product_width_actual").val(parsed_imperial_width_val);
			$("#product_width_imperial").val(parsed_imperial_width_val);
		}); 
	});//]]> 
	</script>

<% end %>

app/views/products/_product_table.html.erb
<%
=begin %>
  @usage: render by calling the "productTable" helper in products_helper.rb
      productTable(@products, imperial, activityColumn)
<%
=end %>
<table id = "productTable">
  <%= productTableHeaders(imperial, activityColumn, search) %> 
	<% products.each do |product| %>
    <%= productTableRow(product, imperial, activityColumn, search) %>
	<% end %>
</table>

app/views/products/_product_table_headers.html.erb
<%
=begin %>
  @usage: render by calling the "productTable" helper in products_helper.rb
      productTable(@products, imperial, activityColumn)
<%
=end %>
<tr>
  <td style="width:100px"></td>
  <td class="productTableHeader">Species</td>
	<td class="productTableHeader"><%= Product.thickness_header(imperial) %></td>
	<td class="productTableHeader">X</td>
	<td class="productTableHeader"><%= Product.width_header(imperial) %></td>
	<td class="productTableHeader">Grade</td>
	<td class="productTableHeader"><%= Product.length_header(imperial) %></td>
	<td class="productTableHeader"><%= Product.volume_header(imperial) %></td>
	<td class="productTableHeader">Details</td>
	<% if activityColumn %>
		<td class="productTableHeader">Active / Inactive</td>
	<% end %>
	<% if search %>
		<td class="productTableHeader">Region</td>
		<td class="productTableHeader">Supplier</td>
	<% end %>
</tr>

app/views/products/_product_table_row.html.erb
<%
=begin %>
  @usage: render by calling the "productTable" helper in products_helper.rb
      productTable(@products, imperial, activityColumn)
<%
=end %>
<tr>
	<td><%= render 'photos/lightbox_tag', {:photo => product.primary_photo} %></div></td>
	<td><%= product.species.name %></td>
	<td><%= product.thickness(imperial) %></td>
	<td><%= " X " %></td>
	<td><%= product.width(imperial) %></td>
	<td><%= product.grade.name %></td>
	<td><%= product.length(imperial) %></td>
	<td><%= product.volume(imperial) %></td>
	<td><%= product.shortDetails %></td>
	<% if activityColumn %>
		<td><%= product.is_active ? "Active" : "Inactive" %></td>
	<% end %>
	<% if search %>
		<td><%= product.region %></td>
		<td><%= link_to(product.company.name, product.company) %></td>
	<% end %>
	<% if @employee.can_manage?(@company.id) %>
		
	<% end %>
</tr>

app/views/products/edit.html.erb
<div id="container">	
	<div id="content">
		<h1>Editing product</h1>
		<div id="MainText" class="gradient2">		
			<% if notice %>
  			<p class="notice"><%= notice %></p>
			<% end %>
			<% if alert %>
				<p class="alert"><%= alert %></p>
			<% end %>	
			<div id="specialForms">
				<%= render 'form' %>
				<div  style="clear: left;">
					<%= link_to 'My Inventory', products_path %> |
					<%= link_to 'My Species', species_index_path %> |
					<%= link_to 'My Grades', grades_path %> 
				</div>
			</div>
		</div>
			<div class= "footer">
				<%=render :partial => 'layouts/footer'%>
			</div>
	</div>
</div>

app/views/products/index.html.erb
<div id="content">
	<h1><%= @company.name %> Inventory</h1>
	<div id="UserInfo">
		<%= render 'companies/quickCompanyBio' %>
	</div> <!-- end div#UserInfo -->
	<% if @employee.can_manage?(@company.id) %>    				
		<table id="buttonHolder">
		  <tr>
				<td><%= button_to 'Add Product', new_product_path, :method => :get , :class => "genericButton" %></td>
  			<td><%= button_to 'Add Species', new_species_path, :method => :get , :class => "genericButton"  %></td>
  			<td><%= button_to 'Add Grade', new_grade_path, :method => :get , :class => "genericButton"  %></td>
  			<td><%= button_to 'My Species', species_index_path, :method => :get , :class => "genericButton" %></td>
  			<td><%= button_to 'My Grades', grades_path, :method => :get, :class => "genericButton"  %></td>
			</tr>
		</table>				
	<% end %>
				
	<div id ="results" class="gradient2">
		<% if @employee.can_manage?(@company.id) %>   
			<div style="float:left;">
			  <div style="float:left; margin-right:10px">
  				<%= label_tag "view_products_all", "All", :class => "smallLabel" %>
          <%= radio_button_tag "view_products", "all", true, :class => "update_products" %>
        </div>
        <div style="float:left; margin-right:10px">
          <%= label_tag "view_products_active", "Active", :class => "smallLabel" %>
          <%= radio_button_tag "view_products", "active", false, :class => "update_products" %>
        </div>
        <div style="float:left; margin-right:10px">
          <%= label_tag "view_products_inactive", "Inactive", :class => "smallLabel" %>
          <%= radio_button_tag "view_products", "inactive", false, :class => "update_products" %>
        </div>
			</div>							
		<% end %>
		<div style="float:right;margin-right:10px;">
      <div style="float:left; margin-right:10px">
        <%= label_tag "unit_imperial", "Imperial", :class => "smallLabel" %>
        <%= radio_button_tag "unit", "imperial", true, :class => "update_products" %>
      </div>
      <div style="float:left; margin-right:10px">
        <%= label_tag "unit_metirc", "Metric", :class => "smallLabel" %>
        <%= radio_button_tag "unit", "metric", false, :class => "update_products" %>
      </div>
		</div>
		<div id="productTableContainer" class="productTableContainer" >
			<div id="productTable"></div>
		</div>
	</div>
	<div class= "footer">
		<%=render :partial => 'layouts/footer'%>
	</div>
</div>
<%= addUpdateProductsOnChange %>

app/views/products/new.html.erb
<div id="container">	
	<div id="content">
		<h1>Add Product</h1>
		<div id="MainText" class="gradient2">
			<% if notice %>
    			<p class="notice"><%= notice %></p>
			<% end %>
			<% if alert %>
				<p class="alert"><%= alert %></p>
			<% end %>			
			<div id="specialForms">
				<%= render 'form' %>
				<div  style="clear: left;">
					<%= link_to 'My Inventory', products_path %> |
					<%= link_to 'My Species', species_index_path %> |
					<%= link_to 'My Grades', grades_path %> 
				</div>
			</div>
		</div>
				<div class= "footer">
					<%=render :partial => 'layouts/footer'%>
				</div>
	</div>
</div>

app/views/products/show.html.erb
<div id="container">	
	<div id="content">
		<h1>Add Product</h1>
		<div id="MainText" class="gradient2">
			<div id="specialForms">
				<p>
				  <b>Is active:</b>
				  <%= @product.is_active %>
				</p>
				
				<p>
				  <b>Thickness:</b>
				  <%= @product.thickness_metric_gross %>
				</p>
				
				<p>
				  <b>Width:</b>
				  <%= @product.width_metric_gross %>
				</p>
				
				<p>
				  <b>Details:</b>
				  <%= @product.details %>
				</p>
				
				<p>
				  <b>Length:</b>
				  <%= @product.length_metric_lower %>
				</p>
				
				
				<%= link_to 'Edit', edit_product_path(@product) %> |
				<%= link_to 'Back', products_path %>
			</div>
		</div>
				<div class= "footer">
					<%=render :partial => 'layouts/footer'%>
				</div>
	</div>
</div>

app/views/products/table.js.erb
$("#productTable").replaceWith("<%= j productTable(@products, @imperial, @activityColumn, @search) %>")
<% if @search %>
	$("#results_tag").html('<h2><%= j @results_tag %></h2>')
<% end %>